url: https://anatby.github.io
baseurl:
title: Anat Ben-Yaacov
description: PhD Student in Computer Science Education
#theme: al-folio
author:
  name: "Anat Ben-Yaacov"
  email: "anat.ben-yaacov@weizmann.ac.il"
